# Generated by Django 4.1.5 on 2023-01-25 06:36

import Person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_alter_child_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=1, validators=[Person.models.validate_age]),
            preserve_default=False,
        ),
    ]
