# Generated by Django 4.1.5 on 2023-01-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Мороженое',
                'verbose_name_plural': 'Мороженые',
            },
        ),
        migrations.CreateModel(
            name='IceCreamShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('icecreams', models.ManyToManyField(to='IceCream.icecream')),
            ],
            options={
                'verbose_name': 'Магазин мороженого',
                'verbose_name_plural': 'Магазины мороженого',
            },
        ),
    ]
