# Generated by Django 4.1.5 on 2023-01-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IceCream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecream',
            old_name='name',
            new_name='Название',
        ),
    ]
